# 파이썬을 활용한 행렬연산 (NumPy)

## 강의를 시작하며
본 파일에는 '파이썬을 활용한 행렬연산 Numpy' 강의를 진행하며 활용한 주제들이 표시되어 있습니다.

우선 강의를 수강하며 스스로 주어진 문제에 적합한 코드를 작성해보세요.
또한 복사본을 하나 만들어 강의가 끝난 뒤에도 스스로 채워넣으며 복습용으로 활용하여도 좋습니다.

본 강의는 학생 중심의 학습 환경을 조성하기 위하여 학습자 중심의 학습과 학습자-교수자 간 적극적인 상호 소통을 지향합니다.
강의 중 모르는 부분이 있다면 교수자에게 편히 질문해주시기 바랍니다.

---
# 0. 파이썬 실습 환경 구성
본 파일은 Python 3 설치 환경을 필요로 합니다.

## 0-1. NumPy 설치 및 import

In [1]:
# NumPy 설치 및 import하기
#pip install numpy
import numpy as np

## 0-2. NumPy를 사용하는 이유

NumPy array는 Python list보다 연산 속도가 빠르다.

이유:

- 배열 안에는 동일한 타입의 데이터만 저장한다. (메모리 주소 할당하지 않음)
- C array 형태로 데이터가 저장된다. (인터프레터 언어 vs 컴파일 언어)

In [2]:
# 문제: 두 (1000 X 1000) 배열의 원소합 (element-wise sum) 구하기
import time
import numpy as np

In [3]:
start = time.time()

# 문제 환경 초기화
np.random.seed(2023)
result = np.empty((1000, 1000), dtype = int)
test1 = np.random.randint(0, 10, 1000)
test2 = np.random.randint(0, 10, 1000)

# 비교 1. for-loop을 활용한 Python list 연산
for i in range(1000):
	for j in range(1000):
    		result[i,j] = test1[i] + test2[j]
		
end = time.time()
print(result)
print(f"Python list 사용 연산 시간: {end - start:.5f} 초")

[[13  8 13 ... 15 16 12]
 [15 10 15 ... 17 18 14]
 [12  7 12 ... 14 15 11]
 ...
 [10  5 10 ... 12 13  9]
 [13  8 13 ... 15 16 12]
 [11  6 11 ... 13 14 10]]
Python list 사용 연산 시간: 1.73037 초


In [4]:
start = time.time()

# 문제 환경 초기화
np.random.seed(2023)
result = np.empty((1000, 1000), dtype = int)
test1 = np.random.randint(0, 10, 1000)
test2 = np.random.randint(0, 10, 1000)

# 비교 2. NumPy 연산
result = test1.reshape(1000, 1) + test2.reshape(1, 1000)

end = time.time()
print(result)
print(f"NumPy 사용 연산 시간: {end - start:.5f} 초")

[[13  8 13 ... 15 16 12]
 [15 10 15 ... 17 18 14]
 [12  7 12 ... 14 15 11]
 ...
 [10  5 10 ... 12 13  9]
 [13  8 13 ... 15 16 12]
 [11  6 11 ... 13 14 10]]
NumPy 사용 연산 시간: 0.00498 초


In [5]:
del start, end, result, test1, test2, i, j

---
# 1. N차원 배열 (ndarray)

N차원 배열이란?

NumPy 홈페이지에서 발췌한 정의:<br>
*N-dimensional array (ndarray)* is a multidimensional container of items of the same type and size.

즉, 같은 타입과 크기를 가지는 원소들을 저장하는 어떤 한 다차원의 컨테이너를 의미합니다.<br>
*컨테이너: 자료형을 저장하는 객체

조금 더 이해하기 쉬운 표현으로는 2차원 표가 다차원으로 확장된 느낌의 개념으로 이해하시면 좋을 것 같습니다.<br>
그림으로 보면 더욱 이해가 쉽습니다.

<참고> 강의교안 중 N차원 배열 (ndarray)

## 1-1. N차원 배열 생성

In [6]:
# 1차원 배열 생성하기
array_1d = np.array([1, 2, 3])
print(array_1d)

[1 2 3]


In [7]:
# 타입 살펴보기
print(type(array_1d))

<class 'numpy.ndarray'>


In [8]:
# np.array() 메서드 활용하여 리스트로 1차원 배열 생성하기
list_1d = [4, 5, 6]
array_1d = np.array(list_1d)
print(array_1d)

[4 5 6]


In [9]:
# np.array() 메서드 활용하여 튜플로 1차원 배열 생성하기
tuple_1d = (7, 8, 9)
array_1d = np.array(tuple_1d)
print(array_1d)

[7 8 9]


In [10]:
# shape 확인하기
print(array_1d.shape)

# ndim 확인하기
print(array_1d.ndim)

# size 확인하기
print(array_1d.size)

(3,)
1
3


In [11]:
# 2차원 배열 생성하기
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [12]:
# shape 확인하기
print(array_2d.shape)

# ndim 확인하기
print(array_2d.ndim)

# size 확인하기
print(array_2d.size)

(2, 3)
2
6


In [13]:
# 3차원 배열 생성하기 (P)

# shape 확인하기

# ndim 확인하기

# size 확인하기


## 1-2. N차원 배열의 데이터 타입 지정

In [14]:
# 예시 데이터를 리스트로 저장하기
list_1d = [0, 1, 2]

# 정수형으로 지정하기
array_1d_int = np.array(list_1d, dtype = int)
print(array_1d_int)
print(array_1d_int.dtype)

# 실수형으로 지정하기
array_1d_float = np.array(list_1d, dtype = float)
print(array_1d_float)
print(array_1d_float.dtype) 

# 불형으로 지정하기
array_1d_boolean = np.array(list_1d, dtype = bool)
print(array_1d_boolean)
print(array_1d_boolean.dtype) # boolean

# 문자형으로 지정하기
array_1d_string = np.array(list_1d, dtype = str)
print(array_1d_string)
print(array_1d_string.dtype) # unicode 문자열

[0 1 2]
int32
[0. 1. 2.]
float64
[False  True  True]
bool
['0' '1' '2']
<U1


In [15]:
# 기 지정된 배열의 데이터 타입을 임의로 변경하기 (P)
# 힌트: .astype() 메서드 사용하기


## 1-3. 정해진 형식의 N차원 배열 생성

In [16]:
# 모든 요소가 0인 N차원 배열 생성하기
array_zeros = np.zeros([2, 2])
print(array_zeros)

# 모든 요소가 1인 N차원 배열 생성하기
array_ones = np.ones([3, 4])
print(array_ones)

# 모든 요소가 지정된 fill_value인 N차원 배열 생성하기
array_full = np.full([2, 3], 'fill_val')
print(array_full)

# NxN (또는 NxM) shape를 가진 대각 원소가 1인 행렬 생성하기
array_I = np.eye(3, 3) # I_n := identity matrix of size n
print(array_I)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[['fill_val' 'fill_val' 'fill_val']
 ['fill_val' 'fill_val' 'fill_val']]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# 예시 배열 생성하기
array_2d = np.array([[1,2,3],
                     [4,5,6]])

# 예시 배열을 모든 요소가 0인 배열의 형식으로 변형하기
array_2d_to_zeros = np.zeros_like(array_2d)
print(array_2d_to_zeros)

# 예시 배열을 모든 요소가 1인 배열의 형식으로 변형하기
array_2d_to_ones = np.ones_like(array_2d)
print(array_2d_to_ones)

# 예시 배열을 모든 요소가 지정된 fill_value인 배열의 형식으로 변형하기
array_2d_to_full = np.full_like(array_2d, 123) # 주의: 예시 배열의 dtype과 fill_value의 dtype 일치
print(array_2d_to_full)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[123 123 123]
 [123 123 123]]


In [18]:
# np.empty() 로 N차원 배열 생성하기 (P)


## 1-4. 특정 범위의 값을 가지는 N차원 배열 생성

In [19]:
# 비교: 파이썬 내장함수 range()
list_range = list(range(0, 10, 2)) # start, stop, step
print(list_range)

[0, 2, 4, 6, 8]


In [20]:
# NumPy의 arange()
array_arange = np.arange(0, 10, 2) # start, stop, step
print(array_arange)

[0 2 4 6 8]


In [21]:
# NumPy의 linspace()
array_linspace = np.linspace(0, 10, 5) # start, stop, num
print(array_linspace)

[ 0.   2.5  5.   7.5 10. ]


In [22]:
# np.linspace()의 num 값의 의미 (P)

# np.linspace()의 stop 값을 포함하지 않는 방법 (P)


In [23]:
# NumPy의 logspace() (상용로그)
array_logspace = np.logspace(1, 10, 10) # start, stop, num
print(array_logspace)

# 밑이 2인 log의 logspace()
array_logspace_base_2 = np.logspace(1, 10, 10, base = 2) # start, stop, num
print(array_logspace_base_2)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


## 1-5. N차원 배열의 난수 생성

In [24]:
# 정규 분포에서 표본을 추출하는 난수 생성 함수 작성하기
array_randn = np.random.randn(10)
print(array_randn)

array_normal = np.random.normal(0, 1, 10)
print(array_normal)

# 퀴즈: 두 함수의 차이점은?


[ 0.69654803 -1.0331129   0.93760248  0.90217129  0.17582227 -0.94776332
  0.66042408 -0.79433292 -1.25403555 -0.98349519]
[-0.92125921  0.76571083 -0.88392416 -1.11435209 -0.02040838 -0.71859861
 -0.50795652 -1.40011116  1.4871072  -0.47287719]


In [25]:
# 데이터 시각화 라이브러리 matplotlib을 설치 및 import 하기
# pip install matplotlib
import matplotlib.pyplot as plt

array_normal_1d = np.random.normal(0, 1, 5) # loc, scale, size
print(array_normal_1d)

array_normal_2d = np.random.normal(0, 1, (2, 3)) # size는 NxM으로도 지정 가능
print(array_normal_2d)

[-0.23080926 -1.39164432  0.68579092  0.38685056  0.66624969]
[[ 1.03060403  2.35678414  0.35297852]
 [-1.12999766 -0.69690044  0.29329286]]


In [26]:
# matplotlib 활용하여 시각화하기 (P)


In [27]:
# 균등 분포에서 표본을 추출하는 난수 생성 함수 작성하기
array_rand = np.random.rand(10) # ~ U(0, 1)
print(array_rand)

[0.8708515  0.56108491 0.07369003 0.74677489 0.83000676 0.93983706
 0.68247926 0.65925898 0.45068459 0.83744249]


In [28]:
# matplotlib 활용하여 시각화하기 (P)


In [29]:
# 랜덤한 정수를 생성하는 함수 작성하기
array_randint = np.random.randint(1, 10, 10) # low, high, size; sample from discrete uniform [low, high)
print(array_randint)

[5 8 8 8 7 4 1 7 9 4]


In [30]:
# matplotlib 활용하여 시각화하기 (P)


## 1-6. 랜덤 시드 (seed) 값을 고정하여 난수 제어

In [31]:
# 시드 값을 이용해 난수의 발생 지점을 고정하기 (P)


---
# 2. N차원 배열 인덱싱 (indexing)

## 2-1. NumPy 기본 인덱싱

In [32]:
# 1차원 배열 생성하기
np.random.seed(2023)
array_1d = np.random.randint(1, 10, 10)
print(array_1d)

# 배열의 첫번째 인자 추출하기
print(array_1d[0]) # list 인덱싱과 동일

# 범위로 인덱싱하기 (슬라이싱)
print(array_1d[0:1]) # list 인덱싱과 동일; array[start, end] = [start, end)

[8 7 8 2 4 5 5 7 6 1]
8
[8]


In [33]:
# 2차원 배열 생성하기 (P)

# 배열의 첫번째 인자 추출하기

# 범위로 인덱싱하기 (슬라이싱)


## 2-2. Fancy 인덱싱 활용

Fancy indexing은 한 NumPy 배열에 대해

- 또 다른 NumPy 배열
- Python list
- 정수 시퀀스 e.g. range()

를 활용하여 NumPy 배열을 인덱싱할 수 있도록 해주는 기법입니다.

In [34]:
# 1차원 배열 난수 생성하기
np.random.seed(2023)
array_1d = np.random.randint(1, 10, 10)
print(array_1d)

# 1차원 배열 Fancy 인덱싱하기
index = [0, 1, 2] # np.array([0, 1, 2])도 가능
print(array_1d[index])

[8 7 8 2 4 5 5 7 6 1]
[8 7 8]


In [35]:
# 2차원 배열 난수 생성하기 (P)

# 2차원 배열 Fancy 인덱싱하기


## 2-3. 불형 & 조건 연산자 인덱싱

In [36]:
# 1차원 배열 난수 생성하기
np.random.seed(2023)
array_1d = np.random.randint(1, 10, 5)
print(array_1d)

# Boolean 리스트를 이용한 불형 인덱싱하기
boolean_list = [True, False, True, False, False]
print(array_1d[boolean_list])

[8 7 8 2 4]
[8 8]


In [37]:
# 조건 연산자를 활용하여 조건에 맞는 배열의 값만 출력하기 (P)


---
# 3. N차원 배열 연산법

## 3-1. 배열 연산 - 기본

Python 연산자와 동일한 연산 수행이 가능합니다.

In [38]:
# 예시 배열 생성하기
array_1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
array_2 = np.array([[5, 5, 5],
                    [5, 5, 5],
                    [5, 5, 5]])

In [39]:
# 덧셈하기 (P)


In [40]:
# 뺄셈하기 (P)


In [41]:
# 곱셈하기 (요소별 곱셈) (P)


In [42]:
# 나눗셈하기 (요소별 나눗셈) (P)


In [43]:
# 몫, 나머지 구하기 (P)


In [44]:
# 제곱, 제곱근 구하기 (P)


In [45]:
# n제곱, n제곱근 구하기 (P)


## 3-2. 배열 연산 - 내적 & 역행렬

### 선형대수학 복습: 내적
선형대수학에서 $m \times n$ 행렬 $A$와 $n \times p$ 행렬 $B$를 내적한 $n \times p$ 행렬 $C$는
$$
A \cdot B = C
$$
로 정의합니다.

$A, B, C$ 각 행렬의 원소는
$$
\begin{bmatrix}
    a_{11} & a_{12} & \cdots & a_{1n}\\
    a_{21} & a_{22} & \cdots & a_{2n}\\ 
    \vdots & \vdots & \ddots & \vdots\\ 
    a_{m1} & a_{m2} & \cdots & a_{mn} 
\end{bmatrix}
\cdot
\begin{bmatrix}
    b_{11} & b_{12} & \cdots & b_{1p}\\
    b_{21} & b_{22} & \cdots & b_{2p}\\ 
    \vdots & \vdots & \ddots & \vdots\\ 
    b_{n1} & b_{n2} & \cdots & b_{np} 
\end{bmatrix}
=
\begin{bmatrix}
    c_{11} & c_{12} & \cdots & c_{1p}\\
    c_{21} & c_{22} & \cdots & c_{2p}\\ 
    \vdots & \vdots & \ddots & \vdots\\ 
    c_{m1} & c_{m2} & \cdots & c_{mp} 
\end{bmatrix}
$$

$$
c_{ij}= a_{i1} b_{1j} + a_{i2} b_{2j} +\cdots+ a_{in} b_{nj} = \sum_{k=1}^n a_{ik}b_{kj}
$$
와 같이 표현할 수 있습니다.

NumPy에서는 내적을 포함한 다양한 행렬 연산을 지원합니다.

In [46]:
# 예시 2차원 배열 생성하기
array_1 = np.array([[1, 2],
                    [3, 4]])
array_2 = np.array([[2, 3],
                    [4, 5]])

In [47]:
# 2차원 배열의 내적 계산하기
print(np.dot(array_1, array_2))

[[10 13]
 [22 29]]


In [48]:
# 임의의 크기로 세 개의 행렬 A, B, C를 만들어 모두 내적하기
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
C = np.array([[1],
              [2],
              [3],
              [4]])

# 내적 계산 (P)


## 3-3. 배열 연산 - 값 대체

In [49]:
# 예시 1차원 배열 생성하기
np.random.seed(2023)
array_rand = (np.random.rand(5)) * 4 # ~ U(0, 4)
print(array_rand)

[1.28795322 3.56168981 2.35220902 0.50638437 0.56536489]


In [50]:
# 절댓값 계산하기 (P)

# 올림하기

# 내림하기

# 반올림하기

# 버림하기


## 3-4. 배열 연산 - 기초통계량 계산

In [51]:
# 2차원 배열 생성하기
np.random.seed(2023)
array_2d = np.random.randint(1, 10, (2, 4))
print(array_2d)

[[8 7 8 2]
 [4 5 5 7]]


In [52]:
# 배열 내 원소들 중 최솟값 구하기 (P)

# 배열 내 원소들 중 최댓값 구하기

# 배열 원소들의 합 구하기

# 배열 원소의 평균값 구하기

# 배열 원소의 표준편차 구하기

# 배열 원소의 누적 합 구하기

# 배열 원소의 중앙값 구하기


기초통계량을 계산하는 메서드 중 최소값, 최대값을 계산하는 메서드 앞에 `arg-` 접두사를 붙여 해당 결과에 해당하는 인덱스를 반환할 수 있습니다.

In [53]:
# arg 함수 알아보기 (P)
# 배열 내 원소들 중 최솟값의 인덱스를 구하기

# 배열 내 원소들 중 최댓값의 인덱스를 구하기


최소, 최대 외에도 다양한 조건을 활용하여 해당 조건을 만족하는 인덱스를 반환하도록 하는 `np.where()` 메서드의 사용법을 익혀봅시다.

In [54]:
# 1차원 배열 생성하기
np.random.seed(2023)
array_1d = np.random.randint(1, 10, 5)
print(array_1d)

[8 7 8 2 4]


In [55]:
# np.where() 로 5 이하의 값들의 인덱스를 반환하기 (P)


**<심화>** 결측치가 있는 배열에서 최대, 최소, 합계 등을 계산하는 방법을 배워봅시다.

In [56]:
# 심화: 결측치가 있는 배열
array_2d_nan = np.array([[1, np.nan],
                         [3, 4]])
print(array_2d_nan)

[[ 1. nan]
 [ 3.  4.]]


In [57]:
# NaN 값이 있으면 최솟값/최댓값/합계 계산이 제대로 작동하지 않음
print(np.min(array_2d_nan))
print(np.max(array_2d_nan))
print(np.sum(array_2d_nan))

nan
nan
nan


In [58]:
# 해결방법 (P)


## 3-5. 배열 연산 - 지수/로그/삼각 함수

In [59]:
# 예시 배열 생성하기 (P)
array_1 = np.array([[1, 2],
                    [3, 4]])

# 자연지수함수 구하기

# 자연로그함수 구하기

# 상용로그함수 구하기

# pi 값 출력하기


In [60]:
# 삼각함수 sin값 구하기 (P)

# 삼각함수 cos값 구하기

# 삼각함수 tan값 구하기

# 삼각함수 tanh값 구하기


In [61]:
# sigmoid 함수 구현하기 (P)
x = np.linspace(-10, 10, 20) # linspace 배열: [-10, 10] with size of 20

# matplotlib으로 시각화하기


## 3-6. 배열 연산 - 비교 연산

In [62]:
# 예시 배열 생성하기
array_1 = np.array([[1, 2],
                    [3, 4]])
array_2 = np.array([[2, 2],
                    [2, 2]])

# 비교 연산자를 활용하여 논리 변수 (불형) 배열 출력하기 (P)


## 3-7. 브로드캐스팅 (broadcasting)

In [63]:
# shape이 다른 두 배열의 연산에 브로드캐스팅이 적용되는 방식 보기
# 행 (또는 열)이 같은 크기일 경우: 열 (또는 행)을 따라 계산을 확장할 수 있음.

# 브로드캐스팅이 가능한 조건 1
'''
1. 차원의 크기가 1일때 가능하다
즉, 두 배열 간의 연산에서 최소한 하나의 배열의 차원이 1이라면 (0번 축이든 1번 축이든; 1행이든 1열이든) 가능하다.
예시:
[[a, b, c],   +   [g, h, i]   ->   [[a + g, b + h, c + i],
 [d, e, f]]                         [d + g, e + h, f + i]]
'''
# 예시 1
array_1 = np.array([[1, 2, 3],
                    [4, 5, 6]])
array_2 = np.array([2, 2, 2])
print(array_1 + array_2)

'''
예시:
[[a],       [d, e, f]        [[a + d, a + e, a + f],
 [b],   +               ->    [b + d, b + e, b + f],    
 [c]]                         [c + d, c + e, c + f]]
 '''
# 예시 2
array_3 = np.array([[1], 
                    [2],
                    [3]])
array_4 = np.array([5, 10, 15])
print(array_3 + array_4)

[[3 4 5]
 [6 7 8]]
[[ 6 11 16]
 [ 7 12 17]
 [ 8 13 18]]


In [64]:
# 브로드캐스팅이 가능한 조건 2
'''
2. 차원의 짝이 맞을 때 가능하다
즉, 차원에 대해 기준이 되는 축의 size가 동일하면 브로드캐스팅이 가능하다.
예시:
[[[a, b],        [[s, t],        [[[a + s, b + t],
  [c, d],         [u, v],          [c + u, d + v],    
  [e, f]],   +    [w, x]]   ->     [e + w, f + x]],
 [[g, h],                         [[g + s, h + t],
  ...                               ...
  [q, r]]]                         [q + w, r + x]]]
'''
# 예시
array_5 = np.array([[[1, 2], 
                     [3, 4],
                     [5, 6]],
                    [[7, 8],
                     [9, 10],
                     [11, 12]],
                    [[13, 14],
                     [15, 16],
                     [17, 18]]])
array_6 = np.array([[1, 2], 
                    [3, 4],
                    [5, 6]])
print(array_5 + array_6)

[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[ 8 10]
  [12 14]
  [16 18]]

 [[14 16]
  [18 20]
  [22 24]]]


In [65]:
# np.array_equal 함수와 np.array_equiv 함수의 차이점을 비교연산/브로드캐스팅 으로 이해하기
print(np.array_equiv([1, 2], [1, 2]))
print(np.array_equal([1, 2], [1, 2]))
print(np.array_equiv([1, 2], [[1, 2], [1, 2]]))
print(np.array_equal([1, 2], [[1, 2], [1, 2]]))

True
True
True
False


## 3-8. NumPy의 벡터 기반 연산

In [66]:
# 시간 계산용 time 패키지 import 하기
import time

In [67]:
# 예시 배열 생성하기
np.random.seed(2023)
array_1 = np.random.randint(1, 10, 10000000) 
array_2 = np.random.randint(1, 10, 10000000)

In [68]:
# 비교 1. for-loop을 활용한 sum 연산
sum = 0
start = time.time()
for i in array_1:
	sum += i
end = time.time()
print("Sum 값:", sum)
print(f"for-loop 사용 sum 연산 시간: {end - start:.5f} 초")

# 비교 2. NumPy 벡터연산을 활용한 sum 연산 (P)
sum = 0
start = time.time()
################# 빈칸을 메우세요
end = time.time()
print("Sum 값:", sum)
print(f"NumPy 벡터연산 사용 sum 연산 시간: {end - start:.5f} 초")

Sum 값: 49989525
for-loop 사용 sum 연산 시간: 7.32939 초
Sum 값: 0
NumPy 벡터연산 사용 sum 연산 시간: 0.00100 초


In [69]:
# 비교 1. for-loop을 활용한 내적 연산
dot = 0
start = time.time()
for i, j in zip(array_1, array_2):
	dot += i * j
end = time.time()
print("Dot product 값:", dot)
print(f"for-loop 사용 내적 연산 시간: {end - start:.5f} 초")

# 비교 2. NumPy 벡터연산을 활용한 내적 연산 (P)
dot = 0
start = time.time()
################# 빈칸을 메우세요
end = time.time()
print("Dot product 값:", dot)
print(f"NumPy 벡터연산 사용 내적 연산 시간: {end - start:.5f} 초")

Dot product 값: 249966893
for-loop 사용 내적 연산 시간: 19.11386 초
Dot product 값: 0
NumPy 벡터연산 사용 내적 연산 시간: 0.00000 초


---
# 4. N차원 배열 정렬

## 4-1. 1차원 배열의 정렬

In [70]:
# 예시 배열 생성하기 (P)
np.random.seed(2023)
array_1d = np.random.randint(1, 10, 10)
print(array_1d)

# 1차원 배열 오름차순 정렬하기 (P)

# 1차원 배열 내림차순 정렬하기 (P)


[8 7 8 2 4 5 5 7 6 1]


## 4-2. 2차원 배열의 정렬

In [71]:
# 예시 배열 생성하기
np.random.seed(2023)
array_2d = np.random.randint(1, 20, (4, 5))
print(array_2d)

[[ 7  2  4  6  1]
 [18 16 16 14  8]
 [ 6 19  4 18 15]
 [17  8 18 17  1]]


In [72]:
# 2차원 배열 row 기준 정렬하기 (P)

# 2차원 배열 column 기준 정렬하기 (P)

# 1차원 배열로 변경하여 전체 배열 정렬하기 (P)


In [73]:
# argsort: 정렬된 배열의 원소들의 출처 (원 배열)에서의 인덱스를 출력하기 (P)


---
# 5. N차원 배열의 형태 변경

## 5-1. reshape 메서드

In [74]:
# 예시 배열 생성하기
array_1d = np.arange(24)
print(array_1d, array_1d.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 1


In [75]:
# 1차원 배열의 shape을 2차원으로 변경하기
array_2d = array_1d.reshape(4, 6)
print(array_2d, array_2d.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 2


In [76]:
# 1차원 배열의 shape을 3차원으로 변경하기 (P)


In [77]:
# 1차원 배열의 shape을 4차원으로 변경하기 (P)


In [78]:
# 계산이 너무 어렵다면? -1을 활용하자! (P)

# 참고) 위 방법은 reshape(1, -1)과 같이 2차원 배열꼴로 변경을 권하는 에러메시지에서 자주 볼 수 있음
'''
에러메시지 예시: 
Expected 2D array, got 1D array instead:
array=[1 5 8 ... 7 6 3]
Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
'''


'\n에러메시지 예시: \nExpected 2D array, got 1D array instead:\narray=[1 5 8 ... 7 6 3]\nReshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.\n'

## 5-2. resize 메서드, ravel 메서드, 그리고 flatten 메서드

In [79]:
# 예시 배열 생성하기
array_1d = np.arange(10)
print(array_1d, array_1d.ndim)

[0 1 2 3 4 5 6 7 8 9] 1


In [80]:
# 1차원 배열을 2차원으로 변경하기 (P)


In [81]:
# 2차원 배열을 1차원으로 변경하기 (P)


In [82]:
# 1차원 배열을 2차원으로 변경하기 (P)


## 5-3. expand_dims() 메서드와 squeeze() 메서드

In [83]:
# 배열의 차원을 row축을 기준으로 한 차원 확장하기
array_1d = np.array([1, 2])
print(array_1d, array_1d.shape)

array_2d_rowwise = np.expand_dims(array_1d, axis = 0)
print(array_2d_rowwise, array_2d_rowwise.shape)

[1 2] (2,)
[[1 2]] (1, 2)


In [84]:
# 배열의 차원을 column축을 기준으로 한 차원 확장하기 (P)


In [85]:
# 배열의 차원을 row축을 기준으로 한 차원 축소하기
array_1d_rowwise_reduced = np.squeeze(array_2d_rowwise, axis = 0)
print(array_1d_rowwise_reduced, array_1d_rowwise_reduced.shape)

[1 2] (2,)


In [86]:
# 배열의 차원을 column축을 기준으로 한 차원 축소하기 (P)


In [87]:
# 3차원 배열을 1차원 배열로 한번에 축소하기 (P)


## 5-4. 전치행렬 (transpose matrix)

전치행렬이란?

<참고> 강의 교안 중 전치행렬 (transpose matrix)의 GIF 예시

In [88]:
# 행렬 A를 전치 행렬로 변환하기
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [89]:
# 전치 행렬 활용하기 (P)

# A.T와 A의 내적 (P)

# A와 A.T의 내적 (P)



In [90]:
# NumPy에 사전 정의된 transpose 함수를 활용하여 계산하기
print(np.transpose(A)) 

[[1 4]
 [2 5]
 [3 6]]


전치행렬 외에도 NumPy의 linalg 모듈을 활용하면 역행렬을 구할 수 있습니다.

In [91]:
# NumPy의 linalg 모듈 활용하여 역행렬 구하기 (P)


In [92]:
# NumPy의 linalg 모듈 활용하여 만든 역행렬 검증하기 (P)


---
# 6. N차원 배열의 병합/분할

## 6-1. N차원 배열에 원소 추가하기

In [93]:
# 1차원 배열 생성하기
array_1d = np.arange(1, 13)
print(array_1d)

# 1차원 배열에 원소 추가하기 (P)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [94]:
# 2차원 배열 생성하기
array_2d = np.arange(1, 13).reshape(3, 4)
print(array_2d)

# 2차원 배열에 행을 기준으로 원소 추가하기 (P)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [95]:
# 2차원 배열에 열을 기준으로 원소 추가하기 (P)


In [96]:
# 2차원 배열을 1차원으로 변형하여 원소 추가하기 (P)


## 6-2. N차원 배열에서 원소 삭제하기

In [97]:
# 1차원 배열에서 특정 원소를 위치를 기준으로 삭제하기 (P)


In [98]:
# 특정 원소를 행을 기준으로 삭제하기 (P)


## 6-3. append/concatenate 메서드를 활용하여 두 배열을 합치기

서로 다른 두 배열을 1차원 배열로 병합하는 방법을 배워봅시다.

In [99]:
# 두 배열 생성하기
array_1 = np.arange(1, 7).reshape(2, 3)
array_2 = np.arange(7, 13).reshape(2, 3)
print(array_1)
print(array_2)

# 두 배열을 1차원 배열로 병합하기 (P)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


이번에는 서로 다른 두 배열을 2차원 배열로 병합하는 방법을 배워봅시다.<br>
먼저, 행을 기준으로 병합하는 방법입니다.

In [100]:
# 두 배열 생성하기
array_1 = np.arange(1, 7).reshape(2, 3)
array_2 = np.arange(7, 13).reshape(2, 3)
print(array_1)
print(array_2)

# 두 배열을 행을 기준으로 병합하기 - append (이어붙이기) (P)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [101]:
# 두 배열을 행을 기준으로 병합하기 - concatenate (병합하기) (P)


In [102]:
# NumPy에 정의된 vstack() 메서드 활용하기
print(np.vstack((array_1, array_2))) # concatenate와 매우 유사

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


이번에는 서로 다른 두 배열을 2차원 배열로 병합하는 방법을 배워봅시다.

In [103]:
# 두 배열 생성하기
array_1 = np.arange(1, 7).reshape(2, 3)
array_2 = np.arange(7, 13).reshape(2, 3)
print(array_1)
print(array_2)

# 두 배열을 열을 기준으로 병합하기 - append (이어붙이기) (P)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [104]:
# 두 배열을 열을 기준으로 병합하기 - concatenate (병합하기) (P)


In [105]:
# NumPy에 정의된 hstack() 메서드 활용하기
print(np.hstack((array_1, array_2)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


NumPy에서는 1, 2차원 배열 뿐 아니라 N차원 배열에 대해 병합이 가능합니다.

단, 병합하고자 하는 각 N차원 배열 객체의 합칠 axis를 제외하고 나머지 axes의 shape이 전부 동일해야 합니다.

In [106]:
# N차원 배열 생성하기 (e.g. 3차원)
a = np.arange(1, 28).reshape(3, 3, 3)
b = np.arange(29, 38).reshape(3, 3, 1)

# append 사용하기 (P)

# concatenate 사용하기 (P)


## 6-4. 한 배열을 두 개로 분할하기

In [107]:
# 1차원 배열을 분할될 배열 갯수를 지정하여 분할하기
array_1d = np.arange(1, 13)
print(array_1d)
print(np.split(array_1d, 3))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


In [108]:
# 2차원 배열 생성하기
array_2d = np.arange(1, 13).reshape(3, 4)
print(array_2d)


# 한 배열을 행을 기준으로 두 개로 분할하기


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [109]:
# NumPy에 정의된 vsplit() 메서드 활용하기


In [110]:
# 2차원 배열 생성하기
array_2d = np.arange(1, 13).reshape(3, 4)
print(array_2d)

# 한 배열을 열을 기준으로 두 개로 분할하기


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [111]:
# NumPy에 정의된 hsplit() 메서드 활용하기


---
# 7. NumPy 실습 예제

In [112]:
import numpy as np

## 예제 1
원소가 모두 7인 (2, 3, 4) 형태의 numpy.array를 출력하시오.

In [113]:
# 답안


## 예제 2
정수 -50 ~ 50의 범위 안의 난수로 이루어진 (4, 5) 형태의 numpy.array를 출력하고 행을 기준으로 오름차순 정렬한 결과와 전체 배열을 1차원 배열로 변경하여 오름차순 정렬한 결과를 출력하시오.

In [114]:
# 답안


## 예제 3
다음과 같은 파이썬 list가 존재한다. list안에 있는 각 numpy.array의 원소들의 평균값과 표준편차, 중앙값을 순서대로 구하여 구한 순서대로 원소가 이루어진 새로운 list를 구성하고 출력하시오.

- 예시 : 각 배열의 평균값이 3.0, 4.0, 5.0이고 표준편차가 1.5, 1.7, 1.9이며 중앙값이 1.0, 2.0, 3.0 이라면 배열로 구성하여 [3.0, 1.5, 1.0, 4.0, 1.7, 2.0, 5.0, 1.9, 3.0] 으로 출력한다.

In [115]:
sample_list = [
    np.full(3, 8),
    np.array([33, -15, 26]),
    np.linspace(17, 26, 3)
    ]

In [116]:
# 답안


## 예제 4
다음과 같은 numpy.array가 존재한다. 이 배열을 행을 기준으로 3개의 배열로 분할하여 분할된 각 배열의 원소들을 제곱한 결과를 다시 원본 배열에 행을 기준으로 병합하시오. (단, 마지막 출력 결과는 원본 배열과 차원이 같아야 한다)

In [117]:
sample_array = np.arange(2, 20, 2).reshape((3, 3))
print(sample_array)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [118]:
# 답안


## 예제 5
삼각함수의 특수각(0deg, 30deg, 60deg, 90deg)을 numpy.array로 생성한 후 특수각에 해당하는 sin, cos, tan 값을 각각 구하여 파이썬 list에 담은 다음 해당 list에 들어있는 값들을 출력하시오. (단, 값이 무한대라면 "INF" 문자열을 출력할 것)

참고) numpy의 삼각함수는 radian 값을 사용하기 때문에 degree를 radian으로 변경해야합니다.

In [119]:
# 답안


## 예제 6
numpy.array를 이용하여 다음 [예시 패턴]과 같이 출력하시오. (단, 출력 시 반복문을 사용하여 출력한다)

[예시 패턴]<br>
0 1 0 1 0 1 0   
1 0 1 0 1 0 1   
0 1 0 1 0 1 0   
1 0 1 0 1 0 1   
0 1 0 1 0 1 0   
1 0 1 0 1 0 1   
0 1 0 1 0 1 0 

In [120]:
# 답안


## 예제 7
다음 두 행렬에 대하여 내적 연산을 수행한 결괏값을 출력하시오. (단, 결과의 소수점 아래는 제거한다)

In [121]:
array_1 = np.array([[2.1, 3.5],
                 [4.2, 2.7],
                 [2.3, 1.9]])
array_2 = np.array([[5, 2, 3],
                 [1, 3, 5]])

In [122]:
# 답안


## 예제 8
조건 연산자를 활용한 Boolean 인덱싱을 이용하여 다음 배열의 원소들 중 2와 5의 배수만 추출한 결과를 오름차순 정렬하여 (2, 4) 행렬로 출력하시오.

In [123]:
array_1 = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

In [124]:
# 답안


## 예제 9
10진수 100~150 사이에 존재하는 정수를 무작위로 30개 추출하여 (3, 10) 형태의 행렬로 만들고 행과 열을 전치한 결과를 출력하시오.

In [125]:
# 답안


## 예제 10
10진수 10~20 사이에 존재하는 실수형의 수를 무작위로 10,000개 추출하여 100개의 구간에 그래프로 시각화하시오.
(단, 무작위 실수값은 균등한 비율로 추출해야 하며 그래프 시각화 도구는 pyplot 모듈을 사용할 것)

In [126]:
# 답안
